-- Adds the column that maps a DB event to its on-chain escrow event. One
-- contract per network holds every event (the contract's own address lives
-- in env config, NEXT_PUBLIC_ESCROW_CONTRACT_ID — see the doc comment on
-- Event.escrowContractId in schema.prisma for the legacy one-contract-per-
-- event column this predates); what identifies a specific event inside that
-- contract is its 16-byte `event_id` (BytesN<16>), generated by the Go
-- service at `create_event` time (internal/escrow.NewEventID,
-- services/core-go/internal/escrow/wallet.go) and rendered as 32 lowercase
-- hex characters by EventID.String(). Nothing in this repo reads or writes
-- this column yet — it exists so the Go release path (release_reward,
-- resolve_dispute, expire_event) has a DB column to read the on-chain id
-- from once that work lands.
--
-- Nullable, not backfilled: no row has an on-chain event yet, and the id
-- only exists from `create_event` confirmation onward — an event is created
-- in the DB first (status = DRAFT) and only gets its escrowEventId once
-- `create_event` succeeds on-chain.
--
-- The CHECK is the only place the 32-lowercase-hex-character format is
-- enforced — Prisma's schema language has no way to express a regex
-- constraint, so it goes directly into this migration's SQL, same as the
-- format CHECKs already in this file's predecessors.
ALTER TABLE "events" ADD COLUMN "escrowEventId" TEXT;

CREATE UNIQUE INDEX "events_escrowEventId_key" ON "events"("escrowEventId");

ALTER TABLE "events"
ADD CONSTRAINT "events_escrowEventId_format_check"
CHECK ("escrowEventId" IS NULL OR "escrowEventId" ~ '^[0-9a-f]{32}$');
